print("Hello, and welcome to your own fantasy story!")
print()
print("I will ask you a couple of question so we can create your own fantastic story")
name = input("What is your name?")
print()
yourMagicalObject = input("What is the magical object that was given to you for safekeeping?")
print()
yourQuest = input("What is the mission that you need to complete?")
print()
nameOfYourEnemy = input("What is the name of you nemesis?")
print()
yourDestination = input("Where is your quest supposed to end?")
print()
yourCompanion = input("Who is your companion?")
print()
print("Hello", name, "i see that you have", yourMagicalObject, "i hope you are ready to ", yourQuest, "because", nameOfYourEnemy, "awaits at the", yourDestination, "for you and", yourCompanion)
